### PR TITLE
Support Rails 5.0

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by tricknotes** [comment]
@mrfoto WDYT?

**Comment by mrfoto** [comment]
Oh, thanks so much!

I guess we could make it `< 6.0`, wdyt?

**Comment by mrfoto** [comment]
I've rebased and merged in your changes, preserving your commit 😄 

Thanks again, and sorry - this went completely under my radar 😕

**Comment by tricknotes** [comment]
np :-)
Thanks man!

**Pull request closed without merging**
